apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ticketing-frontend

spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`gaurav.club`)
      kind: Rule
      services:
        - name: ticketing-frontend
          port: 80
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ticketing-backend

spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`gaurav.club`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: ticketing-backend
          port: 5000
  tls:
    certResolver: letsencrypt
