apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ticketing-frontend
  namespace: ticketing-project
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`gaurav.club`)
      kind: Rule
      services:
        - name: ticketing-frontend
          port: 80

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ticketing-backend
  namespace: ticketing-project
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`gaurav.club`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: ticketing-backend
          port: 5000

