apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: crm-frontend
  namespace: crm
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`crm.gaurav.club`)
      kind: Rule
      services:
        - name: crm-frontend
          port: 80
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: crm-backend
  namespace: crm
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`crm.gaurav.club`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: crm-backend
          port: 5000
  tls:
    certResolver: letsencrypt

